name: samsara_template_project
description: A new Samsara Engine game project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  samsara:
    path: ../..

  flame: ^1.6.0
  flutter_platform_alert: ^0.3.0
  json5: ^0.8.0
  vector_math: ^2.1.4
  window_manager: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/locales/
    - assets/cards/

    - scripts/

  fonts:
    - family: NotoSansMono
      fonts:
        - asset: assets/fonts/NotoSansMonoCJKsc-Regular.otf
